### ISSUE TITLE
Add geo_point property back into JSON search document

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dtdi-mineral-observation-map#15]
There used to be a coordinates property with datatype geo_point in the mapping file, now for some reason there is not.

```
"coordinates": {
    "type": "geo_point"
  }
```

let's add it back in (probably under locality) so we can use it for spatial queries in elasticsearch.

https://www.elastic.co/guide/en/elasticsearch/guide/1.x/geopoints.html

**Comment by zhongh** [comment]
@zednis Let's fix this little issue quickly too?

**Comment by zednis** [comment]
@zhonghao1014 :+1:
