### ISSUE TITLE
Create JSON search documents for mineral map faceted search

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dtdi-mineral-observation-map#2]
cc: @xgmachina 

Create sample mineral observation JSON documents based on the mapping document at ingest/mappings/mineral-observation.json

documents are for mineral observations and include the following
- mineral info
- locality info
- mindat info

These sample JSON documents can be committed to the repository in a examples/ directory.

**Comment by zednis** [comment]
@zhonghao1014 Is there any progress on this?

**Comment by zednis** [comment]
@kolans could you review the JSON mapping at https://github.com/tetherless-world/dtdi-mineral-observation-map/blob/master/ingest/mappings/mineral-observation.json for the mineral observation search document?  You may have some questions on the JSON structure, send me any questions you have and I should be able to answer them :smile:

**Comment by zhongh** [comment]
@zednis The focus now is I am drafting a framework for representing more mineral info than just the contained elements. Like the ratios, valences of the elements in a chemical. Still looking for a way and consulting Marshall at the same time.

**Comment by zhongh** [comment]
@zednis I will create a sample json document

**Comment by zednis** [comment]
@zhonghao1014 Is there any progress on this?

cc: @xgmachina

**Comment by zhongh** [comment]
As for the lastest push the JSON search documents and mappings are working. Maybe we can close this issue and start making the simple html to see how it works.

**Comment by zednis** [comment]
put the example documents in the add-sample-json-search-document branch.  Let's get the map running on a vm and we can close this issue after that is available in test.

edit: I think we should close this issue when we merge the pull request that includes the sample JSON documents.

**Comment by zhongh** [comment]
Let's me create a pull request, and when the pull request is merged we can close this issue.
