### ISSUE TITLE
JSON search document representation of mindat?

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dtdi-mineral-observation-map#3]
currently the mindat is represented in the ES search document as a simple string (not indexed)

from ingest/mappings/mineral-observation.json

```
"mindat": {
        "type": "string",
        "index": "no"
      },
```

Is this the best representation?  Should the mindat be an object with fields, and if so what should they be?

**Comment by zednis** [comment]
@xgmachina any thoughts on this?

**Comment by xgmachina** [comment]
I need to sit down together with @zhonghao1014 to take a view of the current template of the JSON. @zhonghao1014 are you available on Friday afternoon?

**Comment by zhongh** [comment]
Do we still need this issue? It seems that this one is out-dated. @zednis

**Comment by zednis** [comment]
@zhonghao1014 I think we can close this issue
