### ISSUE TITLE
Add mindat badge for mineral specimen observations

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dtdi-mineral-observation-map#35]
Create a badge like we use for DCO-ID and DOI links in DCO.
- [x] replace RRUFF link with a mindat link (RRUFF is behind a login whereas mindat is public)
- [ ] use `dated-locality-mindat-url`for the badge link?
- [ ] use `dated-locality-mindat-id` for the badge text?

example:
<a href="http://www.mindat.org/loc-20265.html"><img src="http://dcotest.tw.rpi.edu/badges/badge?title=MINDAT&text=loc-20265&color=D14719"></a>

**Comment by zhongh** [comment]
I feel maybe `dated-locality-mindat-url` is more like a piece of info as a "2nd locality" to be displayed along with the locality. And it's usually some parent or nearby locality. I feel it looks nice to display it out as a line

And RRUFF link should definitely go to a badge display.

**Comment by zednis** [comment]
Is there a mindat ID for what we refer to as the mineral specimen?

**Comment by zhongh** [comment]
As far as I am concerned, no. The observations from mindat is only part of the data displayed on rruff. And even for those observations from mindat, they don't have a mindat id.

**Comment by zednis** [comment]
Ok, then let's keep it a RRUFF link.  Is there an RRUFF ID for the specimen we can put on the badge?

**Comment by zednis** [comment]
resolved by #39
