### ISSUE TITLE
What does the link on Remote Dated Locality refer to?

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dtdi-mineral-observation-map#36]
![screen shot 2016-04-06 at 10 25 54 am](https://cloud.githubusercontent.com/assets/1057295/14324431/fdee3b4a-fbe1-11e5-899f-a8d1ed1c897d.png)

The link on remote dated locality in the above screenshot is https://deeptime.tw.rpi.edu/map/browser.html?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22from%22%3A0%2C%22size%22%3A20%7D

what is this link supposed to refer to? Should this link to a mindat URL?

**Comment by zhongh** [comment]
Ooop it seems the url is wrong, I will fix this
