### ISSUE TITLE
Time encoding in mineral observation map?

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dtdi-mineral-observation-map#4]
Should there be time associated with the mineral observations or mineral information in the mineral observation map?

**Comment by xgmachina** [comment]
If you mean the age of the observed mineral species, yes there are two attributes in the table on the rruff site  `Max Age (Ma)` and  `Min Age (Ma)`. `Ma` means million years.
If you mean when the mineral species was observed, I do not see it in the rruff/ima site or the mindat site, there are cited publications for the localities of those observations but not all publications have a date.

**Comment by zednis** [comment]
To verify:
- The datetime of when the mineral was observed at the locality (aka the observation time) is not important at this time
- The age of the specimen, modeled with a min and a max age and represented in millions of years, is important.

**Comment by zhongh** [comment]
I think we can close this too as we already have time encodings with mineral specimens.
