### ISSUE TITLE
Update min/max age facets to use 50 Ma intervals

### ISSUE THREAD

**Issue by zednis** [tetherless-world/dtdi-mineral-observation-map#41]
Josh Golden suggested we use a bin size of 50 Ma for the min and max age range facets

> Generally, the graphs that we are producing use a bin size of 50 Ma, so it would be nice be able to use that range. 

We currently have the ranges 0-100, 100-200, 200+

![screen shot 2016-04-13 at 10 32 28 am](https://cloud.githubusercontent.com/assets/1057295/14501348/127cd946-0163-11e6-8ff1-459b2a1c8cf2.png)

We should update this to 0-50, 50-100, 100-150, ... 700+ ?

I am not sure where we should put the upper-limit on our bins; the default facet size is 15 so that would get us to 700+ as our 15th facet entry.

Let's try it to 700+ and see how it looks.

**Comment by zednis** [comment]
@zhonghao1014 any updates?

**Comment by zhongh** [comment]
With 50 Ma interval up to 700 Ma, the browser looks like:
![screen shot 2016-04-27 at 1 30 21 pm](https://cloud.githubusercontent.com/assets/11859381/14861685/414eb0a4-0c7c-11e6-8d83-f3b76acbefb6.png)
When certain facets are selected:
![screen shot 2016-04-27 at 1 30 42 pm](https://cloud.githubusercontent.com/assets/11859381/14861687/4301a604-0c7c-11e6-82d2-efb6427846a4.png)
What do you think? I feel it looks bulky in the age facets.

**Comment by zednis** [comment]
I think we should push it and then ask Josh Golden (source of original request) if he likes it.  We should also ask other users (especially Bob Hazen) what they think of the facet with these ranges.

If the users like the change we keep it, if not we revert.

What do you think @xgmachina @kolans ?
